import {createTheme} from '@shopify/restyle';

import {color} from './color-palette';

export const restyleTheme = createTheme({
  colors: {
    primary: color.Black1,
    secondary: color.Black2,
    blue: color.Blue,
    gray: color.Gray,
    white: color.White,
    green: color.Green,
    red: color.Red,
    white1: color.White1,
    gray8: color.Gray8,
    gray9: color.Gray9,
    gray10: color.Gray10,
  },
  spacing: {
    '-10': -10,
    '1': 1,
    '2': 2,
    '3': 3,
    '4': 4,
    '5': 5,
    '6': 6,
    '7': 7,
    '8': 8,
    '9': 9,
    '10': 10,
    '11': 11,
    '12': 12,
    '13': 13,
    '14': 14,
    '15': 15,
    '16': 16,
    '17': 17,
    '18': 18,
    '19': 19,
    '20': 20,
    '21': 21,
    '22': 22,
    '23': 23,
    '24': 24,
    '25': 25,
    '26': 26,
    '27': 27,
    '28': 28,
    '29': 29,
    '30': 30,
  },
  textVariants: {
    normal: {
      fontStyle: 'normal',
      fontWeight: '400',
      fontSize: 16,
      lineHeight: 19,
      color: 'primary',
    },
    one: {
      fontStyle: 'normal',
      fontWeight: '600',
      fontSize: 14,
      lineHeight: 19,
      color: 'primary',
    },
    two: {
      fontStyle: 'normal',
      fontWeight: '600',
      fontSize: 16,
      lineHeight: 19,
      color: 'primary',
    },
    three: {
      fontStyle: 'normal',
      fontWeight: '600',
      fontSize: 18,
      lineHeight: 22,
      color: 'primary',
    },
    four: {
      fontStyle: 'normal',
      fontWeight: '400',
      fontSize: 14,
      lineHeight: 19,
      color: 'primary',
    },
    five: {
      fontStyle: 'normal',
      fontWeight: '400',
      fontSize: 14,
      lineHeight: 17,
      color: 'primary',
    },
    six: {
      fontStyle: 'normal',
      fontWeight: '400',
      fontSize: 12,
      lineHeight: 16,
      color: 'primary',
    },
    seven: {
      fontStyle: 'normal',
      fontWeight: '600',
      fontSize: 24,
      lineHeight: 34,
      color: 'primary',
    },
    eight: {
      fontStyle: 'normal',
      fontWeight: '400',
      fontSize: 18,
      lineHeight: 22,
      color: 'primary',
    },
    nine: {
      fontStyle: 'normal',
      fontWeight: '400',
      fontSize: 12,
      lineHeight: 15,
      color: 'primary',
    },
    ten: {
      fontStyle: 'normal',
      fontWeight: '400',
      fontSize: 14,
      lineHeight: 18,
      color: 'primary',
    },
    eleven: {
      fontStyle: 'normal',
      fontWeight: '400',
      fontSize: 10,
      lineHeight: 12,
      color: 'primary',
    },
    twelve: {
      fontStyle: 'normal',
      fontWeight: '600',
      fontSize: 10,
      lineHeight: 12,
      color: 'primary',
    },
    thirteen: {
      fontStyle: 'normal',
      fontWeight: '500',
      fontSize: 14,
      lineHeight: 17,
      color: 'primary',
    },
    fourteen: {
      fontStyle: 'normal',
      fontWeight: '600',
      fontSize: 12,
      lineHeight: 18,
      color: 'primary',
    },
    fiveteen: {
      fontStyle: 'normal',
      fontWeight: '600',
      fontSize: 24,
      lineHeight: 34,
      color: 'primary',
    },
    sixteen: {
      fontStyle: 'normal',
      fontWeight: '500',
      fontSize: 12,
      lineHeight: 15,
      color: 'primary',
    },
  },
});
export type RestyleTheme = typeof restyleTheme;
